.github/workflows/build-and-test.yml
CONTRIBUTORS.md
Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountServicesView.swift
Sources/SpeziAccount/Login.swift
Sources/SpeziAccount/Resources/de.lproj/Localizable.strings
Sources/SpeziAccount/Resources/en.lproj/Localizable.strings
Sources/SpeziAccount/SignUp.swift
Sources/SpeziAccount/Username and Password/Localization/Localization+Login.swift
Sources/SpeziAccount/Views/AccountServiceButton.swift
Tests/UITests/TestApp.xctestplan
Tests/UITests/TestApp/AccountTests/AccountTestsView.swift
Tests/UITests/TestApp/AccountTests/TestAccountConfiguration.swift
Tests/UITests/TestApp/FeatureFlags.swift
Tests/UITests/TestApp/TestAppDelegate.swift
Tests/UITests/TestAppUITests/AccountLoginTests.swift
Tests/UITests/TestAppUITests/AccountResetPasswordTests.swift
Tests/UITests/TestAppUITests/AccountSignUpTests.swift
Tests/UITests/TestAppUITests/EmptyAccountServicesTests.swift
Tests/UITests/TestAppUITests/XCUIApplication+TestPrimaryButton.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj
Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme

Currently, when there are no `AccountService`s set up the `AcountServicesView` just displays nothing instead of the button. Especially for developers new to the framework ecosystem, they might be unfamiliar that AccountServices are set up globally and that the respective Signup/Login buttons are place automatically.
This PR tries to avoid this problem by giving a visual hint on why no `AccountServiceButton`s are shown. 
* Improved diagnostics when no `AccountService`s are set up.
@PSchmiedmayer We might consider an alternative where we don't display the diagnostic message but only print the message to the app logger. Are there any guidelines on how to deal with (configuration) issues like these in the Spezi framework ecosystem?
Additionally, the PR fixes some missing translations and …

Show a message when no account services are set up

---

Sources/SpeziAccount/Username and Password/Shared/ValidationRule.swift
Sources/SpeziAccount/Views/VerifiableTextGridRow.swift

- Make a few APIs public before we jump to 0.5.0 to ensure that we can use verifiable text grid row in a few different projects before the new verifiable textfields will be tagged with 0.5.0
- Make `VerifiableTextGridRow` public and improve the 0.4.X API surface

Make VerifiableTextGridRow Public & Improve API Surface

---

Sources/SpeziAccount/AccountConfiguration.swift
Sources/SpeziAccount/AccountOverview.swift
Sources/SpeziAccount/AccountSetup.swift
Sources/SpeziAccount/AccountStorageStandard.swift
Sources/SpeziAccount/AccountValue/Keys/PersonNameKey.swift
Sources/SpeziAccount/Resources/de.lproj/Localizable.strings
Sources/SpeziAccount/Resources/en.lproj/Localizable.strings
Sources/SpeziAccount/Views/AccountOverview/AccountKeyEditRow.swift
Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift
Sources/SpeziAccount/Views/AccountOverview/NameOverview.swift
Sources/SpeziAccount/Views/AccountOverview/PasswordChangeSheet.swift
Sources/SpeziAccount/Views/AccountSetup/DefaultAccountSetupHeader.swift
Sources/SpeziAccount/Views/AccountSetup/ExistingAccountView.swift
Sources/SpeziAccount/Views/SignupForm.swift
Sources/SpeziAccount/Views/UserIdPasswordEmbeddedView.swift
Tests/UITests/TestApp/AccountTests/AccountTestsView.swift
Tests/UITests/TestAppUITests/AccountOverviewTests.swift
Tests/UITests/TestAppUITests/AccountSetupTests.swift
Tests/UITests/TestAppUITests/DocumentationHintsTests.swift
Tests/UITests/TestAppUITests/Utils/SignupView.swift

Currently, we automatically place a `NavigationStack` in the `AccountSetup` and `AccountOverview` views which causes due to nested NavigationStacks like in https://github.com/StanfordSpezi/SpeziOnboarding/issues/21.
This PR removes the NavigationStack dependence from the `AccountSetup` view by presenting the `SignupForm` as a sheet. Further, the `AccountOverview` now requires to be placed into a NavigationStack and doesn't automatically create one by itself.
* `AccountSetup` doesn't use a NavigationStack anymore by presenting the `SignupForm` as a sheet.
* The `AccountSetup` doesn't place itself automatically in a NavigationStack anymore and thus requires one to be present in the view hierarchy already.
Documentation was updated to reflect those new requirements.
Tests were updated and …

Remove NavigationStacks from Setup and Overview and display SignupForm as a sheet

---

Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountConfiguration.swift
Sources/SpeziAccount/AccountNotifyStandard.swift
Sources/SpeziAccount/AccountService/Wrapper/NotifyStandardBackedAccountService.swift
Sources/SpeziAccount/AccountService/Wrapper/StandardBacked.swift
Sources/SpeziAccount/AccountService/Wrapper/StorageStandardBackedAccountService.swift
Sources/SpeziAccount/SpeziAccount.docc/Setup Guides/Initial Setup.md
Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift
Tests/UITests/TestApp/AccountTests/AccountTestsView.swift
Tests/UITests/TestApp/AccountTests/TestStandard.swift
Tests/UITests/TestAppUITests/AccountOverviewTests.swift
Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme

Currently, there is no way for an App to distinguish between Account logout and removal. This is especially important if the App associates other data (questionnaires, additional user information) with the user account that must be deleted as well.
This PR adds the `AccountNotifyStandard` constraint that allows to get notified about an account removal.
* Add `AccountNotifyStandard`
Documentation was added and updated.
Tests were added to verify functionality.

Introduce the AccountNotifyStandard

---

.github/workflows/build-and-test.yml
CONTRIBUTORS.md
Sources/SpeziAccount/AccountHeader.swift
Sources/SpeziAccount/AccountOverview.swift
Sources/SpeziAccount/Resources/de.lproj/Localizable.strings
Sources/SpeziAccount/Resources/en.lproj/Localizable.strings
Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift
Sources/SpeziAccount/Views/AccountOverview/PasswordChangeSheet.swift
Sources/SpeziAccount/Views/AccountSummaryBox.swift
Tests/UITests/TestApp/AccountTests/AccountTestsView.swift
Tests/UITests/TestAppUITests/AccountOverviewTests.swift

Like described in issue #25, some applications like the Spezi Template application could display some additional information such as licensing information or other settings at the bottom of the Account Overview.
Furthermore, some developers might want to do it the other way around and link to account information within a settings page.
Add footer components to AccountOverview, as suggested by @PSchmiedmayer
Implement an additional "AccountHeader" that looks something like the one in the Apple Settings app, as suggested by @Supereg
This PR adds two major things. 
1. A customizable content section ViewBuilder to the `AccountOverview`. Simply pass any view as a trailing closure of AccountOverview and it will be rendered as a Section right between the other AccountOverview information and the …

Add Customizable Area to AccountOverview

---

Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountService/Wrapper/NotifyStandardBackedAccountService.swift
Sources/SpeziAccount/AccountService/Wrapper/StorageStandardBackedAccountService.swift
Sources/SpeziAccount/AccountService/Wrapper/_StandardBacked.swift

We currently don't expose the `StandardBacked` protocol to the outside. The protocol can be helpful do more clearly inspect the type of an account service. Therefore, we expose the protocol with an underscore.
* Made `_StandardBacked` public.
* Documentation was added.
--

Make the StandardBacked protocol visible to the outside

---

Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift

Projects like SpeziFirebase need to verify authentication credentials on security related operations. This was already implemented in #36 for the SingleEditRow and the SecurityOverview. We forgot to identity, that the account deletion is also considered security sensitive. Therefore, we inject the same modifier in the primary AccountOverview view.
This PR is required for https://github.com/StanfordSpezi/SpeziFirebase/pull/23 to be merged.
* Inject security related modifiers in the AccountOverview
--
--

Inject security related modifier in main overview screen

---

Sources/SpeziAccount/ViewModifier/AccountRequiredModifier.swift
Sources/SpeziAccount/ViewModifier/VerifyRequiredAccountDetailsModifier.swift

With the upgrade to Observable the `@Environment` property wrapper behaves differently to the `@EnvironmentObjet` property wrapper. The two property wrappers behave differently when there is no object in the environment. While `@EnvironmentObject` results in a runtime crash upon access, `@Environment` crashes as soon as the view is getting rendered.
To achieve maximum compatibility, we changed how the `accountRequired(_:setupSheet:)` and `verifyRequiredAccountDetails(_:)` are implemented, to avoid a situation where we request access to the `Account` object when it is not available. This allows us to use those modifiers with greater flexibility.
* Allow  `accountRequired(_:setupSheet:)` and `verifyRequiredAccountDetails(_:)` modifiers to be used (in disabled state) if Account is not …

Do not inject Account modifiers if not enabled

---

Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountService/Wrapper/StandardBacked.swift
Sources/SpeziAccount/AccountSetupViewStyle/AccountSetupViewStyle.swift
Sources/SpeziAccount/AccountSetupViewStyle/EmbeddableAccountSetupViewStyle.swift
Sources/SpeziAccount/AccountSetupViewStyle/IdentityProviderViewStyle.swift
Sources/SpeziAccount/AccountSetupViewStyle/UserIdPasswordAccountSetupViewStyle.swift
Sources/SpeziAccount/AccountValue/AccountKey.swift
Sources/SpeziAccount/Mock/MockSignInWithAppleProvider.swift
Sources/SpeziAccount/Mock/MockSimpleAccountService.swift
Sources/SpeziAccount/SpeziAccount.docc/Setup Guides/Using the Account Object.md
Sources/SpeziAccount/Views/AccountSetup/AccountServiceButtonList.swift
Sources/SpeziAccount/Views/AccountSetup/AccountServicesSection.swift
Sources/SpeziAccount/Views/AccountSetup/ExistingAccountView.swift
Sources/SpeziAccount/Views/AccountSetup/IdentityProviderSection.swift
Sources/SpeziAccount/Views/SignupForm.swift
Sources/SpeziAccount/Views/UserIdPasswordEmbeddedView.swift
Sources/SpeziAccount/Views/UserIdPasswordPrimaryView.swift
Sources/SpeziAccount/Views/UserIdPasswordResetView.swift
Tests/UITests/TestApp/AccountTests/TestAccountService.swift
Tests/UITests/TestApp/AccountTests/TestStandard.swift
Tests/UITests/TestAppUITests/AccountSetupTests.swift
Tests/UITests/TestAppUITests/Utils/SignupView.swift
Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme

This PR restores the functionality of the `AccountStorageStandard`. There was an issue with SpeziAccount where account creation wasn't correctly picked up by the configured storage standard.
We had to reengineer some parts of the SpeziAccount infrastructure to ensure the Storage Standard is called at all times.
* Fix storage standard
--
New tests cases were added to verify the functionality and protect us against regressions.

Restore functionality of the storage standard

---

Package.swift
README.md
Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountConfiguration.swift
Sources/SpeziAccount/AccountNotifyConstraint.swift
Sources/SpeziAccount/AccountService/AccountService.swift
Sources/SpeziAccount/AccountService/Configuration/AccountServiceConfiguration.swift
Sources/SpeziAccount/AccountService/Configuration/SupportedAccountKeys.swift
Sources/SpeziAccount/AccountService/EmbeddableAccountService.swift
Sources/SpeziAccount/AccountService/Wrapper/NotifyStandardBackedAccountService.swift
Sources/SpeziAccount/AccountService/Wrapper/StandardBacked.swift
Sources/SpeziAccount/AccountService/Wrapper/StorageStandardBackedAccountService.swift
Sources/SpeziAccount/AccountSetupViewStyle/AccountSetupViewStyle.swift
Sources/SpeziAccount/AccountStorageConstraint.swift
Sources/SpeziAccount/AccountValue/AccountKey.swift
Sources/SpeziAccount/Model/AdditionalRecordId.swift
Sources/SpeziAccount/SpeziAccount.docc/Account Values/Adding new Account Values.md
Sources/SpeziAccount/SpeziAccount.docc/Account Values/Handling Account Value Storage.md
Sources/SpeziAccount/SpeziAccount.docc/Setup Guides/Custom Storage Provider.md
Sources/SpeziAccount/SpeziAccount.docc/Setup Guides/Initial Setup.md
Sources/SpeziAccount/ViewModifier/AccountServiceButtonModifier.swift
Tests/UITests/TestApp/AccountTests/TestStandard.swift

This PR upgrades to the latest Spezi 1.0 releases. Further, we made our Standard constraints protocol naming consistent with the rest of the ecosystem. Lastly, we replaced a `preconditionFailure` with a log message to avoid some unnecessary crashes.
* Upgrade to latest Spezi 1.0 releases
* Renamed `AccountNotifyStandard` and `AccountStorageStandard` to `AccountNotifyConstraint` and `AccountStorageConstraint` to be more consistent with the rest of the Spezi framework ecosystem.

Upgrade to Spezi 1.0 releases

---

Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountConfiguration.swift
Sources/SpeziAccount/AccountHeader.swift
Sources/SpeziAccount/AccountOverview.swift
Sources/SpeziAccount/AccountSetup.swift
Sources/SpeziAccount/Resources/Localizable.xcstrings
Sources/SpeziAccount/ViewModel/AccountOverviewFormViewModel.swift
Sources/SpeziAccount/Views/AccountOverview/AccountKeyOverviewRow.swift
Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift
Sources/SpeziAccount/Views/AccountOverview/NameOverview.swift
Sources/SpeziAccount/Views/AccountOverview/PasswordChangeSheet.swift
Sources/SpeziAccount/Views/AccountOverview/SecurityOverview.swift
Sources/SpeziAccount/Views/AccountOverview/SingleEditView.swift
Sources/SpeziAccount/Views/AccountSetup/FollowUpInfoSheet.swift
Sources/SpeziAccount/Views/Preview/AccountDetailsReader.swift

As of right now the desired way to provide access to the `Account` object for previewing purposes with active account details, is by creating the `Account` instance yourself and putting it into the environment.
With the introduction of the new `previewWith` modifier in Spezi `1.0`, we now have a framework-defined way of configuring modules for Previews. Therefore, this PR adds support to configure the `AccountConfiguration` for previewing purposes.
* Add `AccountConfiguration(building:active:configuration:)` initializer to easily preview Spezi Account using the new spezi `previewWith` modifier.
Documentation was added.
_TBA_
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and …

Allow to supply active account details with the AccountConfiguration for previews

---

Sources/SpeziAccount/AccountValue/Keys/PasswordKey.swift
Tests/UITests/TestAppUITests/AccountOverviewTests.swift
Tests/UITests/TestAppUITests/AccountSetupTests.swift

Previously, we would disable password auto-fill within the simulator to avoid the simulator proposing a pre-filled password that would otherwise interfere with our UI tests. This approach broke with iOS 17.2 simulator and our workaround seems to not always work.
Instead, this PR just avoids using the `.newPassword` content type when running within the simulator.
* Avoid using `.newPassword` text content type when running within the simulator.
Inline docs were added.
--

Do not use .newPassword content type within simulator

---

Sources/SpeziAccount/SpeziAccount.docc/Account Values/Adding new Account Values.md

Prior, there were no code examples for creating a custom DataDisplayView for non-String based values. 
- Highlighted example of creating custom DataDisplayView using an Int-based Value. 
- added sentence highlighting the difference between the default String-based DataDisplayView and a custom DataDisplayView of different value type
- wrote one-sentence description of the example of a HeightValue Key
- inserted code example

Update Adding new Account Values

---

Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountValue/AccountKeyCategory.swift
Sources/SpeziAccount/Views/AccountOverview/NameOverview.swift
Sources/SpeziAccount/Views/AccountSetup/DefaultAccountSetupHeader.swift
Tests/UITests/TestApp/AccountTests/TestAlertModifier.swift

This PR addresses an issue where the `securityRelatedViewModifier` of an account service was not injected into the single row edit view.
* Inject security related modifier in single edit view

Inject security related modifier in single edit view

---

Sources/SpeziAccount/Account.swift
Sources/SpeziAccount/AccountSetup.swift

There was a faulty check resulting in the AccountSetup Header not being displayed when only using Identity Provider.
* Fixed an issue where the AccountSetup Header wouldn't be displayed with only using identity provider.
--
We added another permutation in the Preview section.

Fix appearance of AccountSetup Header when only using identity provider

---

Sources/SpeziAccount/AccountSetup.swift
Tests/UITests/TestAppUITests/AccountSetupTests.swift

The AccountSetup inconsistently treated anonymous account details (still showing the setup views but not reacting to changes when going from anonymous to non-anonymous). This is fixed by this PR.
* Fixed account setup closure not being called if anonymous details were previously associated.
--
--

Fix AccountSetup closure not getting called when anonymous details are associated

---

Package.swift
Sources/SpeziAccount/AccountDetailsCache.swift
Sources/SpeziAccount/AccountValue/Collections/AccountDetails+Codable.swift
Sources/SpeziAccount/AccountValue/Collections/AccountDetails.swift
Sources/SpeziAccount/AccountValue/Keys/AccountDetailsFlags.swift
Tests/SpeziAccountTests/AccountDetailsTests.swift

The current approach of decoding and encoding `AccountDetails` relies on setting the expected `userInfo` keys on the encoder and decoder instance. While is highlighted in documentation, there is no compile-time check that there isn't any mistake in the configuration (e.g., missing keys or values with unexpected type). iOS 17 introduced the `CodableWithConfiguration` protocols that allow to set a configuration type for encoding and decoding.
This PR migrates the current approach to adopting the `EncodableWithConfiguration` protocol and replacing the `Decodable` conformance with `DecodableWithConfiguration`. The requirement to pass a configuration upon decoding is now expressed with the type system and will produce a compiler warning if not done correctly.
* Add `EncodingConfiguration` and …

Encoding and Decoding of AccountDetails with strongly typed configuration

---

Sources/SpeziAccount/AccountStorageProvider.swift
Sources/SpeziAccount/ExternalAccountStorage.swift
Sources/SpeziAccount/Mock/InMemoryAccountService.swift
Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift
Sources/SpeziAccount/Views/AccountOverview/PasswordChangeSheet.swift
Sources/SpeziAccount/Views/AccountOverview/SingleEditView.swift
Sources/SpeziAccount/Views/AccountSetup/ExistingAccountView.swift
Sources/SpeziAccount/Views/AccountSetup/FollowUpInfoSheet.swift
Tests/SpeziAccountTests/AccountNotificationsTests.swift

This PR changes how `CancellationError`s are handled that are returned from an account service. For example, if the `delete()` method of an account service returns an CancellationError we will not show an error dialog but just return to the account overview without dismissing the account overview.
* Handle CancellationErrors thrown from the account service operations.
* Do not allow AccountStorageProvider/load method to be throwing to make it easier for Account Services to interact storage providers.
--
--

Handle CancellationError from account services

---

Sources/SpeziAccount/Environment/AccountRequiredKey.swift
Sources/SpeziAccount/ExternalAccountStorage.swift
Sources/SpeziAccount/Mock/InMemoryAccountService.swift
Sources/SpeziAccount/SpeziAccount.docc/AccountService/Custom Storage Provider.md
Sources/SpeziAccount/SpeziAccount.docc/SpeziAccount.md
Sources/SpeziAccount/ViewModifier/AccountRequiredModifier.swift
Tests/UITests/TestAppUITests/AccountOverviewTests.swift
Tests/UITests/TestAppUITests/AccountSetupTests.swift

Currently, the `accountRequired(_:setupSheet:)` modifier considers any associated account details as a valid account and therefore dismisses the provided setup sheet. However, typically anonymous accounts are not considered full accounts and are only used to have a persistent account identifier. The `AccountSetup` sheet treats anonymous accounts similarly where it still shows all the signup options.
This PR introduces a new flag passed to the `accountRequired(_:considerAnonymousAccounts:setupSheet:)` modifier to control the behavior of anonymous accounts. By default anonymous accounts are treated the same as if no account was present.
* Ignore anonymous accounts with the `accountRequired` modifier by default.
Documentation was updated.
--
By submitting creating this pull request, you …

`accountRequired` modifier should not consider anonymous accounts by default.

---

.github/workflows/build-and-test.yml
Package.swift
Sources/SpeziAccount/Views/AccountSetup/SetupProvider/AccountServiceButton.swift
Sources/SpeziAccount/Views/AccountSetup/SetupProvider/SignupSetupView.swift
Sources/SpeziAccount/Views/DataEntry/BoolEntryView.swift
Sources/SpeziAccount/Views/DataEntry/CaseIterablePickerEntryView.swift
Sources/SpeziAccount/Views/DataEntry/FixedWidthIntegerEntryView.swift
Sources/SpeziAccount/Views/DataEntry/FloatingPointEntryView.swift
Sources/SpeziAccount/Views/DataEntry/StringEntryView.swift
Sources/SpeziAccountMacros/AccountKeyMacro.swift
Tests/SpeziAccountMacrosTests/AccountKeyMacroTests.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj

This PR upgrades to the upcoming release of SwiftSyntax. This allows us to provide additional functionality like verifying the `lexicalContext` of an account details property. This way, we can check that the `@AccountKey` macro can only be applied inside an extension to `AccountDetails`.
* Improve diagnostics around the `@AccountKey` macro.
--
Added additional unit tests to verify the updated diagnostics.

Upgrade to Swift Syntax for Swift 6

---

.github/workflows/pull_request.yml
Package.swift
Sources/SpeziAccount/AccountConfiguration.swift
Sources/SpeziAccount/AccountSetup.swift
Sources/SpeziAccount/AccountStorageProvider.swift
Sources/SpeziAccount/AccountValue/Collections/AccountDetails.swift
Sources/SpeziAccount/AccountValue/Keys/AccountDetailsFlags.swift
Sources/SpeziAccount/Mock/InMemoryAccountService.swift
Sources/SpeziAccount/Mock/InMemoryAccountStorageProvider.swift
Sources/SpeziAccount/Views/AccountSetup/SetupProvider/AccountServiceButton.swift
Sources/SpeziAccount/Views/AccountSetup/SetupProvider/SignInWithAppleButton.swift
Sources/SpeziAccountMacros/SpeziAccountDiagnostic.swift
Tests/UITests/TestApp/AccountTestsView.swift
Tests/UITests/TestApp/Features.swift
Tests/UITests/TestApp/Utils/AccountDetails+Default.swift
Tests/UITests/TestAppUITests/AccountSetupTests.swift
Tests/UITests/TestAppUITests/Utils/XCUIApplication+AccountSetup.swift
Tests/UITests/TestAppUITests/Utils/XCUIApplication+TestApp.swift
Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme

The `AccountSetup` accepts a `setupComplete` closure that will get called once the setup is completed giving the parent view the opportunity to perform additional checks or navigation steps based on the outcome. While a `AccountService` always calls an `ExternalStorageProvider` before submitting account details to `Account`, they have been decoupled in v2.0.0 and an `ExternalStorageProvider` must always return immediacy from its `load` call. In scenarios where account details are not locally cached yet, an `ExternalStorageProvider` returns details that are marked as [incomplete](https://swiftpackageindex.com/stanfordspezi/speziaccount/documentation/speziaccount/accountdetails/isincomplete).
`AccountSetup` didn't check for this flag and forwarded incomplete details to the `setupComplete` …

Make sure to only pass complete account details to the account setup complete closure

---

Sources/SpeziAccount/Views/AccountOverview/AccountOverviewForm.swift

`AccountOverview` allows specifying a `closeBehavior` value, which is documented as controlling whether a "Close" button is shown as part of the view.
However, this value is currently ignored, and the close button is always shown.
- `AccountOverview`: fix `closeBehavior` not having any effect
n/a
n/a

AccountOverviewForm: take `closeBehavior` into account

---

Sources/SpeziAccount/AccountSetup.swift
Sources/SpeziAccount/Environment/SignupProviderCompliance.swift
Sources/SpeziAccount/Views/DataEntry/DateOfBirthPicker.swift

After addressing , `SpeziAccount` wasn't building for me with the following errors/warnings:
1. Error
```
SpeziAccount/Views/DataEntry/DateOfBirthPicker.swift:102:17
main actor-isolated property 'layout' can not be mutated from a Sendable closure
layout = value
^
```
2. Error:
```
SpeziAccount/Sources/SpeziAccount/AccountSetup.swift:163:26
main actor-isolated property 'compliance' can not be mutated from a Sendable closure
self.compliance = compliance
^
```
4. Warning:
```
SpeziAccount/Sources/SpeziAccount/Environment/SignupProviderCompliance.swift:152:13
capture of 'action' with non-sendable type '(SignupProviderCompliance?) -> Void' in a `@Sendable` closure
action(compliance?.compliance)
^
```
* Fix the three build errors/warnings I was receiving.
No new features were introduced that …

Fix Sendable-related Build Errors

---

Package.swift
Sources/SpeziAccount/Views/AccountSetup/FollowUpInfoSheet.swift
Sources/SpeziAccount/Views/AccountSummaryBox.swift
Sources/SpeziAccount/Views/SignupFormHeader.swift

* Move FormHeader to SpeziViews as ListHeader to reuse this view across other Spezi libraries.

Move FormHeader to SpeziViews as ListHeader

---

Sources/SpeziAccount/AccountValue/AccountKey.swift
Sources/SpeziAccount/AccountValue/AccountKeyCategory.swift
Sources/SpeziAccount/AccountValue/AccountKeyMacros.swift
Sources/SpeziAccount/AccountValue/AccountKeyOptions.swift
Sources/SpeziAccount/AccountValue/Configuration/AccountOperationError.swift
Sources/SpeziAccount/AccountValue/Configuration/AccountValueConfiguration.swift
Sources/SpeziAccount/AccountValue/Configuration/ConfiguredAccountKey.swift
Sources/SpeziAccount/ExternalAccountStorage.swift
Sources/SpeziAccount/Mock/InMemoryAccountStorageProvider.swift
Sources/SpeziAccount/Mock/MockBoolKey.swift
Sources/SpeziAccount/Mock/MockDoubleKey.swift
Sources/SpeziAccount/Mock/MockNumericKey.swift
Sources/SpeziAccount/Resources/Localizable.xcstrings
Sources/SpeziAccount/SpeziAccount.docc/AccountKey/Adding new Account Values.md
Sources/SpeziAccount/ViewModel/AccountOverviewFormViewModel.swift
Sources/SpeziAccount/Views/AccountOverview/AccountKeyOverviewRow.swift
Sources/SpeziAccount/Views/SignupForm.swift
Sources/SpeziAccountMacros/AccountKeyMacro.swift
Tests/SpeziAccountMacrosTests/AccountKeyMacroTests.swift
Tests/UITests/TestApp/AccountTestsView.swift
Tests/UITests/TestApp/Features.swift
Tests/UITests/TestApp/TestAppDelegate.swift
Tests/UITests/TestApp/Utils/OptionsKey.swift
Tests/UITests/TestApp/Utils/TestStandard.swift
Tests/UITests/TestAppUITests/AccountOverviewTests.swift
Tests/UITests/TestAppUITests/Utils/XCUIApplication+TestApp.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj
Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme

An AccountKey was always assumed to be mutable and the `AccountConfiguration` fully dictated if it was displayed to the user or not.
This PR adds a new optional `options` requirement to `AccountKey`s that allows to specify this behavior by two new options `display` and `mutable`. Refer to the inline documentation for the exact semantic of these two options. `[.display, .mutable]` will stay the default.
```swift
/// The account key supports to be displayed to the user.
///
/// An Account Key always implicitly supports read access. Therefore, when `display` is supported, a ``DataDisplayView`` is required to be specified (or relying on a default implementation fo
/// the given type).
/// If ``mutable`` option is set as well, a ``DataEntryView`` is likewise required to be specified.
public …
```

Allow to specify and customize display and mutation behavior of Account Keys

---

CONTRIBUTORS.md
Package.swift
Sources/SpeziAccount/AccountValue/AccountKey+Views.swift
Sources/SpeziAccount/AccountValue/AccountKeyMacros.swift
Sources/SpeziAccount/ExternalAccountStorage.swift
Sources/SpeziAccount/Mock/InMemoryAccountStorageProvider.swift
Sources/SpeziAccount/SpeziAccount.docc/AccountKey/Adding new Account Values.md
Sources/SpeziAccount/Views/AccountOverview/AccountKeyOverviewRow.swift
Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift
Sources/SpeziAccount/Views/DataDisplay/SetupDisplayView.swift
Sources/SpeziAccountMacros/AccountKeyMacro.swift
Sources/SpeziAccountMacros/KeyEntryMacro.swift
Tests/SpeziAccountMacrosTests/AccountKeyMacroTests.swift
Tests/SpeziAccountTests/AccountDetailsCacheTests.swift
Tests/SpeziAccountTests/AccountNotificationsTests.swift
Tests/SpeziAccountTests/SnapshotTesting.swift
Tests/UITests/TestApp/Features.swift
Tests/UITests/TestApp/TestAppDelegate.swift
Tests/UITests/TestApp/Utils/OptionsKey.swift
Tests/UITests/TestAppUITests/AccountOverviewTests.swift
Tests/UITests/TestAppUITests/Utils/XCUIApplication+TestApp.swift
Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme

Currently, the `DataDisplay` view of an account key is only drawn if there is a value added to the `AccountDetails` of a user. This PR adds a new optional protocol you can conform your display view to that allows to also draw UI if the an account value is not yet present. In combination with `display-only` account keys, this can be used to exclusively provide a custom setup experience for an account key.
* Add `SetupDisplayView` as an additional conformance for the display view of an account key.
* `@KeyEntry` macro now supports variadic arguments through Parameter Packs.
Updated docs catalog.
Added UI tests to verify SetupDisplayView is rendered and updated unit tests for macros.
By creating and submitting this pull request, you agree to follow our [Code of …

Introduce `SetupDisplayView` protocol as a way to provide a setup view for account details
